# Generated by Django 4.0 on 2022-03-17 18:34

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(default='', max_length=8)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('family', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('sale', models.IntegerField(blank=True, default=None, null=True)),
                ('sale_duration', models.DateTimeField(blank=True, default=None, null=True)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image_folder', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('image_number', models.IntegerField(blank=True, default=1, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.Computer.get_static_folder)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mbu', models.CharField(default='', max_length=20)),
                ('gpu', models.CharField(max_length=20)),
                ('gpu_type', models.CharField(choices=[('NVIDIA', 'NVIDIA'), ('AMD', 'AMD')], max_length=20)),
                ('cpu', models.CharField(max_length=20)),
                ('cpu_type', models.CharField(choices=[('INTEL', 'INTEL'), ('AMD', 'AMD')], max_length=10)),
                ('memory', models.CharField(choices=[('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB')], max_length=10)),
                ('storage', models.CharField(max_length=20)),
                ('storage_type', models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD'), ('SSD & HDD', 'SSD & HDD')], max_length=10)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.computer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('avatar', models.ImageField(default='profile/default.jpg', upload_to=api.models.Profile.user_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='api.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='api.computer')),
            ],
        ),
    ]
