# Generated by Django 4.0 on 2022-03-10 16:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Computer.get_static_folder),
        ),
        migrations.AddField(
            model_name='computer',
            name='image_folder',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
