# Generated by Django 4.0 on 2022-03-10 16:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_computer_image_computer_image_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='image_folder',
            field=models.CharField(blank=True, default=api.models.Computer.get_media_folder, max_length=30, null=True),
        ),
    ]
