# Generated by Django 4.0 on 2022-03-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_computer_image_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='image_folder',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
