# Generated by Django 4.0 on 2022-03-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_computer_image_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='image_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
