# Generated by Django 4.0 on 2022-03-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_computer_image_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='mbu',
            field=models.CharField(default='', max_length=20),
        ),
    ]
