# Generated by Django 4.0 on 2022-01-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/images/profile/default.jpg', upload_to='static/images/profile/'),
        ),
    ]
