# Generated by Django 4.0 on 2022-02-13 14:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0008_profile_address_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='cpu',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='cpu_type',
            field=models.CharField(choices=[('INTEL', 'INTEL'), ('AMD', 'AMD')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='gpu',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='gpu_type',
            field=models.CharField(choices=[('NVIDIA', 'NVIDIA'), ('AMD', 'AMD')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='memory',
            field=models.CharField(choices=[('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='sale',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='sale_duration',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='storage',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='storage_type',
            field=models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD'), ('SSD & HDD', 'SSD & HDD')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ComputerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(5, 5), (4.5, 4.5), (4, 4), (3.5, 3.5), (3, 3), (2.5, 2.5), (2, 2), (1.5, 1.5), (1, 1)])),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.computer')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
