# Generated by Django 4.0 on 2022-02-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_computer_sale_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
