# Generated by Django 4.0 on 2022-03-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rating_alter_computer_options_delete_computerreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='family',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
