# Generated by Django 4.0 on 2022-03-09 22:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_cart_computer_family_computer_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=api.models.Computer.get_static_folder),
        ),
    ]
