# Generated by Django 4.0 on 2022-03-09 22:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_computer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='image_folder',
            field=models.CharField(blank=True, default=api.models.Computer.get_static_folder, max_length=30, null=True, unique=True),
        ),
    ]
