# Generated by Django 4.0 on 2022-03-09 22:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_computer_image_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='image_folder',
            field=models.CharField(auto_created=True, default=api.models.Computer.get_static_folder, max_length=30, unique=True),
        ),
    ]
