# Generated by Django 4.0 on 2022-03-09 22:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_computer_image_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Computer.get_static_folder),
        ),
    ]
